name 'toml'
maintainer 'Matt Ray'
maintainer_email 'chef@mattray.dev'
license 'Apache-2.0'
description 'Provides TOML Custom Resource'
version '0.1.0'
chef_version '>= 16.0'

issues_url 'https://github.com/mattray/toml-cookbook/issues'
source_url 'https://github.com/mattray/toml-cookbook'
